name: 'deploy-prod'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

vars:
  var1: abc

jobs:
  echoing:
    run-on: ubuntu-latest
    steps:
      run: echo {{ vars.var1}}
  deploy: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Скачать репозиторий
        uses: actions/checkout@v3
      - name: Развернуть в облаке
        id: sls-func
        uses: yc-actions/yc-sls-function@v2
        with:
          yc-sa-json-credentials: ${{ secrets.SA_KEY }}
          # bucket: ${{ secrets.BUCKET }}
          folder-id: ${{ secrets.FOLDER_ID }}
          function-name: 'test-function-actions'
          runtime: 'golang121'
          memory: '256Mb'
          entrypoint: './cmd/function/main.Handler'
          environment: | 
            DEBUG=True
            COUNT=1
          exclude: |
            .git
            .github
          # include: 
          #   - *
          #   ./src
          #   package.json
          # exclude: | 
          #   **/*.ts
          # tags: |
          #   ${{ GITHUB_SHA::6 }}
          #   foo